# Generated by Django 5.2 on 2025-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_chargerequest_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerequest',
            name='amount',
            field=models.FloatField(),
        ),
    ]
